---
apiVersion: v1
kind: Service
metadata:
  name: cloudvistaresort
spec:
  ports:
  - port: 8000
  selector:
    app: cloudvistaresort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvistaresort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudvistaresort
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: cloudvistaresort
    spec:
      containers:
      - name: cloudvistaresort
        image: gcr.io/<PROJECT_ID>/lcloudvistaresort-app-en:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: AWS_BUCKET
          value: "cloudvistaresort-en-xxxx"
        - name: S3_ACCESS_KEY
          value: "xAKIATOKGAW3IXZALD4V3"
        - name: S3_SECRET_ACCESS_KEY
          value: "JJCpR5X1Si9Jkggz7z1EprjD9Qy1ZZ9BMvVnAX7p"
        - name: DB_HOST_NAME
          value: "172.21.0.3"
        - name: DB_USER
          value: "app"
        - name: DB_PASSWORD
          value: "welcome123456"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudvistaresort
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: cloudvistaresort